services:
  nginx:
    image: nginx:latest
    container_name: "nginx"
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      # - laravel
      - mailhog
      - node
    working_dir: /var/www
    volumes:
      - .:/var/www:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl/server.crt:/etc/nginx/ssl/server.crt
      - ./docker/nginx/ssl/server.key:/etc/nginx/ssl/server.key
    restart: always

  node:
    image: node:24
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
      - 9229:9229
    working_dir: /usr/src/app
    tty: true
    environment:
      NODE_ENV: development
      TZ: UTC
      NEXT_PUBLIC_TIMEZONE: Asia/Tokyo
      PRISMA_DATABASE_URL: mysql://docker:docker@db:3306/willfit
    restart: always
    depends_on:
      - db

  mailhog:
    image: axllent/mailpit
    environment:
      MP_WEBROOT: mailpit

  adminer:
    image: adminer
    restart: on-failure
    environment:
      ADMINER_DESIGN: adminer-dark
      ADMINER_DEFAULT_SERVER: host.docker.internal:3306

  db:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: willfit
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "UTC"
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d:ro
      - ./docker/mysql/dump:/docker-entrypoint-initdb.d
      - ./docker/mysql/data:/var/lib/mysql
    restart: on-failure
